### ISSUE TITLE
Keyboard help desactivated when switching french-swiss keyboard to emoji and back to french-swiss keyboard

### ISSUE THREAD

**Issue by wilfridd** [ubports/keyboard-component#100] opened 2019-10-12 16:41 UTC
Little annoying bug found. Tested with app "Notes" or "Teleports" on N5, MX4

**Steps to reproduce**
1) Display language is "English UK"
2) Enable 3 keyboard layouts : EN, FR-CH, EMOJI
3) Spell checking, auto Capitalization, auto Punctuation are set to ON.

With the "earth symbol", select FR-CH -> word suggestion bar is visible:
- Start typing ".", then "space" -> keyboard is uppercase automatically
- Type "F", then "space" 2 times -> "." appears automatically

Select EMOJI -> word suggestion bar is not visible (that's ok)
- type some emoji

Select FR-CH -> word suggestion bar is NOT visible (weird)
- Start typing ".", then "space" -> keyboard is NOT uppercase automatically
- Type "F", then "space" 2 times -> "." does NOT appears automatically

Select EN, word suggestion bar is visible again, auto Cap and auto Punct work again
Select FR-CH, word suggestion bar is visible again, auto Cap and auto Punct work again
Then loop to "select EMOJI" to continue reproducing...

**Expected behavior**
Switch from FR-CH to EMOJI
Type some EMOJI
Switch back to FR-CH, word suggestion bar is still visible , auto Capitalization, auto Punctuation work

**Actual behavior**
Word suggestion bar, auto Cap and auto Punct are disabled when switching from FR-CH to EMOJI and back to FR-CH
Switching OFF/ON Word suggestion bar, auto Cap and auto Punct in "Language & Text" setting  has no effect.
Switch to EN and back to FR-CH makes Word suggestion bar, auto Cap and auto Punct work again.

BR
wilfridd

**Comment by Fuseteam** [comment] 2019-11-21 02:55
The same behavior is present on the dvorak layout and the layout in pr #93

preliminary testing seems to reveal that it adopts the dictionary of the previously selected layout
it just so happens that the emoji layout doesn't have a dictionary

**Comment by Fuseteam** [comment] 2019-12-03 17:42
looking at maliit-server.log it appears these lines looks relevant
```
CRITICAL: Couldn't find word engine plugin for  "fr-ch"
CRITICAL: Couldn't find word engine plugin for  "en@flick"
CRITICAL: Couldn't find word engine plugin for  "en@dv"
```

**Comment by Fuseteam** [comment] 2020-02-19 02:15
```WARNING: void MIMPluginManagerPrivate::_q_setActiveSubView(const QString&, Maliit::HandlerState) "libubuntu-keyboard-plugin.so" "en@flick" is not enabled```
could possibly be the cause

**Comment by Fuseteam** [comment] 2020-02-20 00:59
aha! [this function](https://github.com/ubports/keyboard-component/blob/ddd892a8d25aae7ea67f7222b42349f59301e1d1/src/plugin/inputmethod.cpp#L722) tries to load "fr-ch" or "en@dv" or "en@flick" while it should just load "fr" and "en"

if all language dictionaries have 2 letter codes we could just truncate it at 2 variables in here

**Comment by wilfridd** [comment] 2020-02-27 18:12
Hi Fuseteam,
thank you!
how can test your change? thanks for guidance.
BR
Wilfridd

**Comment by Fuseteam** [comment] 2020-02-28 11:52
@wilfridd i am testing a fix(es) on the flick branch since that experiences the same issue but so far no dice

**Comment by Fuseteam** [comment] 2020-04-30 11:57
hey @wilfridd i finally found a workaround
if you want you can test it by installing pr 128, You'll need to set rootfs to read write, even if temporary, via ut tweak tool

here are the steps
1. sudo ubports-qa install ubports/keyboard-component 128
note: ubports-qa should fail, if it doesn't select "no" when prompted
2. sudo apt install ubuntu-keyboard-english-flick
3. restart maliit-server

tapping and holding on your symbol key should reveal a new a way to access emoji by "flicking". 

note you don't have tap and hold to select the emoji keyboard

it's somewhat experimental so there are some bugs i have yet to work out feel free to list any you find on pr 128

**Comment by Fuseteam** [comment] 2020-05-01 03:38
@wilfridd disregard my previous comment pr 128 is no longer a viable workaround, the idea was scrapped before it could see the light of day

**Comment by wilfridd** [comment] 2020-05-01 16:02
ok.
In the meantime, I've found this workaround:
I switch to french or english KB then back to fr_ch and KB helpers are back with world suggestion too...
BR
w.

**Comment by Fuseteam** [comment] 2020-12-22 12:13
hi @wilfridd can you test the about pull request to see if it works for you?

**Comment by wilfridd** [comment] 2020-12-23 21:25
Hi @Fuseteam 
PR 134. All keybord helpers work on Meizu4 with swiss french layout (devel)
Will test on N5 next.
That's nice!! Thank you!!
W.

**Comment by wilfridd** [comment] 2020-12-28 12:07
Hi @Fuseteam,
It works also on N5

**Comment by Fuseteam** [comment] 2020-12-28 15:40
awesome glad to hear @wilfridd  would mind adding your finding to the pr?

**Comment by wilfridd** [comment] 2021-01-03 16:05
keyboard helpers fixed with swiss french layout
Thanks!

**Comment by lduboeuf** [comment] 2021-01-03 19:57
@wilfridd since the PR is not merged yet, can you reopen that issue ? Will be auto closed when PR is merged

**Comment by wilfridd** [comment] 2021-01-04 18:32
Hi @lduboeuf , issue reopened as requested.
w.

**Comment by wilfridd** [comment] 2021-02-20 08:45
Hi @lduboeuf , @Flohack74,
Currently testing on N5 with new fresh install RC (2021-W07). "Nice to have" means not in RC ?
I had to do a ubports-qa install ubports/keyboard-component 134 to have the fix.
I confirm the fix is working fine.
Should I test something else to have it promoted to RC and next stable?
W.

**Comment by lduboeuf** [comment] 2021-02-20 13:38
> Hi @lduboeuf , @Flohack74,
> Currently testing on N5 with new fresh install RC (2021-W07). "Nice to have" means not in RC ?
> I had to do a ubports-qa install ubports/keyboard-component 134 to have the fix.
> I confirm the fix is working fine.
> Should I test something else to have it promoted to RC and next stable?
> W.

Unfortunatly, this won't go on OTA-16 as it is feature-freezed now. Let see for next upgrade hopefully. cc @UniversalSuperBox ;-)

**Closed as completed** 2021-03-24 17:45 UTC

**Comment by Fuseteam** [comment] 2021-03-27 04:31
awesome this fixed a blocking issue with flick as well

**Comment by lduboeuf** [comment] 2021-03-27 09:08
> awesome this fixed a blocking issue with flick as well

which issue ?

**Comment by Fuseteam** [comment] 2021-03-27 09:46
> > awesome this fixed a blocking issue with flick as well
> 
> which issue ?

the same issue :) it is fixed now 👍
